### ISSUE TITLE
Having emoticons show up in browsers that don't support gifs

### ISSUE THREAD

**Issue by mhb11** [Fantomas42/django-emoticons#3]
@Fantomas42 

I am using your emoticons app for a project in South Asia that targets rural localities and poverty-stricken families. I have a simple forum where users post messages vis-a-vis their daily needs or other observations. 

Most of my users are on phones that don't support javascript and use Opera Mini, a browser that doesn't support animated gifs. So I converted the animated gifs to jpgs (i.e. I just used 1 frame from each gif), but I still haven't been able to get the jpg files to show up. Note that it works fine on less primitive platforms, and that I'm using tags not filters.

I've used jpgs else where on the website, so can confirm that they work fine on opera mini. But I'm unable to get your app to work. Can you suggest what I can do differently?

**Comment by Fantomas42** [comment]
@mhb11 

Do you have edited the EMOTICONS_LIST settings, after converting the gif to jpeg ?
Because by default in this list, each smiley code is linked to a gif file.

Regards

**Comment by mhb11** [comment]
@Fantomas42 

Yes, that's the first thing I did right after replacing the GIF file with a JPG. I went into your settings.py, and changed the reference to .jpg inside emoticons_default_list. Currently I've only tried this with one emoticon - if I can get that to work, I'll replicate it for every other emoticon in the list. 

Any other leads that come to your head I should look at, other than this change in settings.py? Anything in emoticons_tags.py?

Thanks for responding btw.

**Comment by Fantomas42** [comment]
The true question is: 
does the image does not show because of a 404, or because the generated link still use a .gif ?

In the second case, you should check twice your modifications.

Note, do not change directly the emoticons/settings.py file, but define a EMOTICONS_LIST into your project's settings.

**Comment by mhb11** [comment]
Well, I tested this on less primitive platforms, and the .jpg emoticon did show up correctly. This leads me to believe the generated link is correct. I've explicitly checked it too, it ends with a .jpg asset. That's why I thought I'll get in touch with you too, just in case there's something else I'm missing.

Okay, so your advice is to over-ride EMOTICON_LIST in my project's settings. Thanks for the pro-tip.

**Comment by Fantomas42** [comment]
If the generated link is correct, the issue is not coming from the application.

Maybe your conversion from the gif has generated jpegs incompatible with primitive platforms. Because maybe jpeg format exists...

A good test is to try to access directly to the jpeg with a primitive platform, to see if it display or not.

**Comment by mhb11** [comment]
Sounds like good reasoning, I was expecting this test to give me a clue, but strangely, the link directly to the static asset opens up correctly on the primitive device. This has officially entered the territory of highly unusual for me.

Do you happen to have any hosted demo I can quickly try?

**Comment by mhb11** [comment]
Turned out, it wasn't the app, it was the images. I solved it by messing around with the images' meta data. Thanks for your time!
