### ISSUE TITLE
How to selectively print a cheat sheet for the emoticons

### ISSUE THREAD

**Issue by mhb11** [Fantomas42/django-emoticons#4]
Hi there Fantomas42,

If you remember, I've deployed your plugin for a Django app of mine that serves underserved communities in parts of Asia. It's working well, but I'm looking to do a small tweak.

In the help section of my website, I've laid out all the emoticons supported, and how to make them, via this code in my template:
```
{% emoticons_index as emoticons_list %}
{% for emoticons in emoticons_list %}
<p>{{ emoticons.0|emoticons }}    {{ emoticons|join:" " }}</p>
{% endfor %}
```
My users - being semi literate only - are unable to understand that to make an emoticon, they just have to type ONE combination written in front of it. So for instance, to make the blush emoticon, they make all the symbols: :$ :-$ :=$ (instead of just one)

How can I tweak the template tags above such that they only show the FIRST symbol that one has to make, instead of all of them. I still want the rest of the symbols to work though, just don't want to print them. It should be straight forward to code, but I've unable to wrap my head around how to do it in your code. Please advise.

Thanks!

**Comment by Fantomas42** [comment]
{% emoticons_index as emoticons_list %} 
    {% for emoticons in emoticons_list %} 
        <p>{{ emoticons.0|emoticons }} {{ emoticons.0 }}</p> 
    {% endfor %}

**Comment by mhb11** [comment]
Oh okay, just accessing from the dictionary. Thanks.
