### ISSUE TITLE
    "duplicates: %s" % app_config.label) django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: staticfiles

### ISSUE THREAD

**Issue by akamg** [Fantomas42/django-emoticons#6]
Hi, I've been trying  to install this apps in my INSTALLED_APPS, but i keep getting the above error!
and for the registrations procedure to my admin, please where is located the model! from which the emoticons will be imported then registered?

**Comment by Fantomas42** [comment]
Hello,

this error seems related to your settings. Check your INSTALLED_APPS, because django-emoticons does not rely on staticfiles. 

Note, no models are provided, but check emoticons/settings.py

Regards
