### ISSUE TITLE
Corrputed output when using django-emoticons as a template filter

### ISSUE THREAD

**Issue by mhb11** [Fantomas42/django-emoticons#7]
I have a question. I just used django-emoticons inside an `<input>` tag in a Django template like this: `<input type="submit" class="cg cl" style="border:none;background:none;font-weight:bold" value="{{ reply.0.which_group.topic|emoticons }}">`. This ends up giving me corrupted output where the emoticons appear with a `<img class=` tag right next to them. What could be going on?

p.s. great library overall

**Comment by Fantomas42** [comment]
Hello,

django-emoticon is designed to replace text smiley with the appropriate image in HTML,
so it's normal that your HTML is broken. It's a bad idea to use the filter inside an HTML markup.

Regards
